site_name: DnD 5E Homebrew Compendium
site_description: Homebrew classes and subclasses for 5E
site_author: Song
repo_url: https://github.com/NyusSsong/DnD5E_Homebrew_Compendium
edit_uri: edit/master/docs

theme:
  name: material
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.top
    - navigation.path
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.tabs.link
    - tables.responsive

nav:
  - Home: index.md
  - Rules: rules.md
  - Classes:
      - Base Classes:
        - Barbarian: classes/base_classes/barbarian.md
        - Paladin: classes/base_classes/paladin.md
        - Ranger: classes/base_classes/ranger.md
      - Kibbles Tasty:
        - Psion: classes/kibbles/kt_psion.md
        - Warlord: classes/kibbles/kt_warlord.md
      - Valda:
        - Warden: classes/valda/valda_warden.md
  - Magic Items: magic-items.md

markdown_extensions:
  - admonition
  - pymdownx.snippets:
      base_path: docs/snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - toc:
      toc_depth: 0

extra_css:
  - assets/css/custom.css
  - assets/css/magic-items.css
extra_javascript:
  - assets/js/filter-js
  - assets/js/magic-items.js
